### ISSUE TITLE
download file with dest property that does not exist causes file to be downloaded to root.

### ISSUE THREAD

**Issue by freshcodemonger** [michel-kraemer/gradle-download-task#116]
Is there an option to create a destination path where one does not exist?

**Comment by michel-kraemer** [comment]
Yes, this is possible. Just create the directory in a `doFirst` block before downloading:

```gradle
task downloadFile(type: Download) {
    def destDir = "mydirectory"
    doFirst { mkdir destDir}
    src 'http://example.com/index.html'
    dest destDir
}
```

Explanation:

gradle-download-task only creates a destination directory if it equals the build directory or if multiple source files should be downloaded. Otherwise, the `dest` property defines the name of the destination file. See also lines 139-152 in DownloadAction.java.

https://github.com/michel-kraemer/gradle-download-task/blob/b3f492521d6999ad83d83dc871c2785132856bca/src/main/java/de/undercouch/gradle/tasks/download/DownloadAction.java#L139-L152

**Comment by freshcodemonger** [comment]
Thank you !
