### ISSUE TITLE
Download stuck - java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by Xerus2000** [michel-kraemer/gradle-download-task#122]
![image](https://user-images.githubusercontent.com/13354331/47936110-f9356e80-dedc-11e8-9815-62b2cac90481.png)
I have given it a few minutes, but it just doesn't continue. If I try to download the same zip in the browser, it only takes a few seconds, but the plugin somehow doesn't do it.

A while later, this error appeared:
```
Execution failed for task ':kotlinc'.
> java.net.SocketException: Connection reset
```

I am using version 3.4.3 with Gradle 4.10.2

**Comment by michel-kraemer** [comment]
@Xerus2000 Does it work now? Can the issue be closed?

**Comment by Xerus2000** [comment]
Well, I am still wondering why it was stuck for multiple times before it worked.

**Comment by michel-kraemer** [comment]
If it doesn't anymore, I guess it was a temporary network problem.

**Comment by michel-kraemer** [comment]
We can leave the issue open if you like in case someone else experiences the same problems. However, if the issue is not really reproducible and since no one else has ever reported something similar, I really believe you had some kind of temporary network problems. Maybe you're behind a proxy or a firewall treating traffic from your browser differently?

**Comment by Xerus2000** [comment]
Well, the weird thing is that this happened from two totally different networks. But I'm gonna close this now, we can always reopen it if there is evidence.
