### ISSUE TITLE
Option to download from Nexus repository(Private one)

### ISSUE THREAD

**Issue by pradeep-017** [michel-kraemer/gradle-download-task#153]
Hi,
I am working on a Java gradle project. I have few concerns with gradle download task:
1. I want to download files from Nexus repository URL. I need to pass my credentials to get into the repo and download the files. How can we pass credentials and download the files?

2. I see that ApacheURLLister is not working even after I pull it in the dependency. I am getting error like:
`unable to resolve class org.apache.ivy.util.url.ApacheURLLister` 
I also came to know that ApacheURLLister is deprecated. May I know if there's an alternative to this?

Thanks In Advance!!

**Comment by michel-kraemer** [comment]
1. There are options to pass credentials. Please read the 'Authentication' section in the README (https://github.com/michel-kraemer/gradle-download-task#authentication). Let me know if you have trouble configuring the plugin.

2. I didn't know `ApacheURLLister` was deprecated. I don't know any alternative. As the class is provided by `org.apache.ivy`, maybe you should ask the Ivy developers for more information. Feedback would be appreciated so I can update the README if necessary.

I hope this helps. Let me know if you need anything else. Otherwise, please close the ticket. Thanks.
