### ISSUE TITLE
query parameters in src url

### ISSUE THREAD

**Issue by DasShorty** [michel-kraemer/gradle-download-task#335]
**Describe the bug**
Could not stat file. This shows up when i try to use `D:\IdeaProjects\LaudyNetwork\NetworkUtils\src\main\resources\export?languages=en&format=JSON&zip=false`. The Error says that it cannot access the output directory 

**Sample build script**
https://pastes.dev/10ZjnAV60O

**Comment by michel-kraemer** [comment]
I'm sorry but I cannot reproduce this issue with your sample build script. If I execute it as is, I get an error regarding an empty `eachFile` block because there's only one source specified (`An 'eachFile' action can only be added if multiple sources are provided.`). If I comment this block out, I get an HTTP 403 error, just like I get when I open the URL in my web browser.

It seems to me your build script is either broken or everything works as it should. If you can provide more information, I'd be more than happy to help.

**Comment by DasShorty** [comment]
i use now kotlin's native file download
