### ISSUE TITLE
Downloading large files.

### ISSUE THREAD

**Issue by admizh** [michel-kraemer/gradle-download-task#39]
When download a large file, for example * .zip. I stop building before the download is complete - but  file is created in destination dir, this file is broken.
In next executions my file is not downloaded again. because i use `overwrite = false`:
```
download {
        src url
        dest browserZip
        overwrite false
        onlyIfNewer true
    }
```
I suggest using a two-phase downloading. First, use temporary file with the autogenerated name after that rename it to the target file

**Comment by michel-kraemer** [comment]
`onlyIfNewer true` is ineffective in your case because `overwrite false` is checked first. Due to this your request can be implemented very easily in Gradle directly without changing the plugin. I uploaded an example build file:

https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/tempRename.gradle

I hope this helps!

Cheers,
Michel
