### ISSUE TITLE
Feature request: Enable parallel downloads

### ISSUE THREAD

**Issue by jordihs** [michel-kraemer/gradle-download-task#74]
My build script downloads two large files it needs to process. It would really speed up if the files could be downloaded in parallel. Would it be possible to enable this with a flag and some Threading control for downloads? 
Thank you Michel, this plugin is really useful! Cheers.

**Comment by michel-kraemer** [comment]
This is already possible. Take a look at the following build file:

```gradle
plugins {
    id "de.undercouch.download" version "3.1.2"
}

import de.undercouch.gradle.tasks.download.Download

@ParallelizableTask
class ParallelDownload extends Download {}

task downloadFile1(type: ParallelDownload) {
    src 'http://search.maven.org/remotecontent?filepath=de/undercouch/citeproc-java/1.0.1/citeproc-java-1.0.1.jar'
    dest new File(buildDir, "citeproc-java-1.0.1.jar")
}

task downloadFile2(type: ParallelDownload) {
    src 'http://search.maven.org/remotecontent?filepath=de/undercouch/citeproc-java/1.0.1/citeproc-java-1.0.1-javadoc.jar'
    dest new File(buildDir, "citeproc-java-1.0.1-javadoc.jar")
}

task download(dependsOn: [downloadFile1, downloadFile2])
```

We extend the `Download` task and apply the `@ParallelizableTask` annotation. Then we define two tasks downloading a file to two different locations.

Since parallel task execution is an incubating feature in Gradle you have to run the build as follows:

    gradle --parallel -Dorg.gradle.parallel.intra=true download

Both, `--parallel` and the `org.gradle.parallel.intra`, are important! Also, it seems to be important that the `dest` properties of the two tasks are different (for example, you must not set them both to `buildDir`). Otherwise Gradle will think that the outputs of the two tasks are the same and will not execute them in parallel.

If you execute Gradle like this you will see that the two tasks are executed in parallel. Unfortunately, you will only get the progress of one file at the same time. The display will jump back and forth between the two files.

Let me know if this solves your problem. If so, please close the issue.

**Comment by jordihs** [comment]
Hi Michel. Thanks a lot for such a quick and detailed response. I will tinker with this feature; actually, I did try with that when I still used ant.get instead of your plugin, but that was like a year ago. I do wonder when the parallel will leave incubation. But for some reason it didn't work for me. It's too bad that I can't use the same output dir for both because that is what my actual script is doing. But I guess I can download one of the files elsewhere and then move it to the proper destination. 
Anyway, I will close the issue since it doesn't seem to make sense to implement threading when gradle already has it built in. I do suggest that you add a ParallelDownload subclass of your own, with the @ParallelizableTask tag already in, so users can skip the step of doing that in their scripts. 
Anyway, I'll let you know how I did. Thanks again!

**Comment by michel-kraemer** [comment]
> It's too bad that I can't use the same output dir for both because that is what my actual script is doing. 

Sorry, what I meant was you cannot set `dest` to the same property (`buildDir` for example) but - as you can see in the example - you can still specify two different files in the same directory. No need to move the files later. You just have to define the full filenames instead of just the directory.

**Comment by jordihs** [comment]
Okay, got it. I'll try that tomorrow morning. Thanks!

**Comment by jordihs** [comment]
Okay, I got it to work by following your instructions. 
I wanted the parallel execution to be automatic, without flags in the command line, because this is a shared script and it's a pain for everyone to add flags. Then I had some issues adding `org.gradle.parallel.intra` to gradle.properties, it was ignored. 
So for the record, the right way to automate that option is to write it as `systemProp.org.gradle.parallel.intra=true`. for some reason, gradle will not pick it up from the config file otherwise. 
Many thanks for your help with this, now I am very happy with how the script is working. Cheers!
