### ISSUE TITLE
Handle retrying a download

### ISSUE THREAD

**Issue by paour** [michel-kraemer/gradle-download-task#83]
I'm having a problem with this task running on Bitrise: for an unknown reason, it's sometimes stalling on even small downloads. At first I thought it might be a memory problem, but a quick look at your very clean code shows that's clearly not the case (unless it's an issue in HttpClient).

Anyhow, I would be interested in trying the `timeout` parameter you recently added, but I can't find the 3.3.0-SNAPSHOT in jCenter.

I would also like to suggest a `retry n` parameter, which would run the same request again if it fails, a maximum of `n` times.

**Comment by michel-kraemer** [comment]
You can use the following code to switch to the snapshot:

```gradle
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath 'de.undercouch:gradle-download-task:3.3.0-SNAPSHOT'
    }
}

apply plugin: 'de.undercouch.download'
```

> I would also like to suggest a retry n parameter, which would run the same request again if it fails, a maximum of n times.

That's a very good idea actually. I will put this on my TODO list. In the meantime you can implement a very easy workaround. Look at the following recipe that cycles through a number of mirror servers:
https://www.michel-kraemer.com/recipes-for-gradle-download/#recipe-6-mirror-servers

Instead of a list of mirror servers you could just have a counter that you increase until the maximum number of retries has been reached.

Besides, pull requests are very much appreciated if you want to implement the `retry` option yourself 😄 

Cheers,
Michel

**Comment by paour** [comment]
Thanks Michel, that's a pretty cool work-around! I'll queue up the PR request for when I'm in less of a rush :-), great to hear you're open to them.

**Comment by mernst** [comment]
Adding a `retry n` parameter would be very useful.

As a workaround, users can tweak the recipe at https://michelkraemer.com/recipes-for-gradle-download/#recipe-6-mirror-servers, but it would be nicer to build `retry` into gradle-download-task.  That would solve this common need once and for all, in a way that is easy to use and easy to read in a build.gradle file.

**Comment by michel-kraemer** [comment]
I'll pin this issue so it won't be marked as stale again. It's a pretty good idea actually.

**Comment by michel-kraemer** [comment]
@liucc52 In the upcoming gradle-download-task version 4.0.0, there will be a `retries` parameter. I just pushed the commit.
