### ISSUE TITLE
Feature request: Download nested folders

### ISSUE THREAD

**Issue by chronvas** [michel-kraemer/gradle-download-task#85]
Hi, is it possible to download and create folders as they are on a simple directory listing?
eg: http://central.maven.org/maven2/de/undercouch/gradle-download-task/
should create 13 folders with the according files in them

That could be really usefull for my scenario, which I am trying to download different values for different localizations for Android Studio. The way studio creates these localized values is by seperating each localization to folder, like the below screenshot
![screen shot 2017-05-05 at 09 26 56](https://cloud.githubusercontent.com/assets/8863897/25738430/08541ee6-3175-11e7-97ef-8a1c361e8c50.png)

Thanks for your awesome work

**Comment by michel-kraemer** [comment]
Yes, this is possible. As long as the server provides the directory listing in Apache format. See the following build file for an example:
https://github.com/michel-kraemer/gradle-download-task/blob/master/examples/directory.gradle

If you want to recursively download a directory and mirror the structure you have to a write recursive function. This should be easy in Gradle/Groovy.

Please note that we cannot implement such a feature in gradle-download-task directly because all web servers are different and a there is no generic solution that would work everywhere.

I hope this helps. Let me know if you need anything else.
