### ISSUE TITLE
Download file only if missing

### ISSUE THREAD

**Issue by andamian** [michel-kraemer/gradle-download-task#96]
I'm trying to download a file only if it's missing locally. 
To do this, I've added

overwrite false

> gradle downloadFile
> rm build/index.html

>gradle downloadFile
:downloadFile UP-TO-DATE

BUILD SUCCESSFUL

Total time: 0.678 secs

downloadFile shows UP-TO-DATE even if the file is missing locally. Is that the correct behaviour?

Thanks

**Comment by k-mack** [comment]
I'm seeing this on my end as well. The workaround I have found is to remove the generated `.gradle` sub-directory from my project and then run the task again.

**Comment by michel-kraemer** [comment]
This seems to be a duplicate of #105. Which Gradle version are you using?

**Comment by k-mack** [comment]
I am using Gradle 4.2.1.

**Comment by michel-kraemer** [comment]
Have you tried updating it to a newer version?

**Comment by michel-kraemer** [comment]
I think this issue might have something to do with https://github.com/gradle/gradle/issues/1168. If I perform the steps described in https://github.com/gradle/gradle/issues/1168#issuecomment-341028209, I can reproduce the problem. It seems Gradle refers to cached information from the `.gradle` directory when checking if a task is up-to-date or not. If this information is somehow invalid, the task will not be executed. I suppose it happens if you rename a task (as described in the comment) or if you update Gradle (or maybe gradle-download-task??) or something similar. The easy solution seems to be to just delete the `.gradle` directory. After this everything should be fine again.
