### ISSUE TITLE
feature request: onlyIfChanged

### ISSUE THREAD

**Issue by kenyee** [michel-kraemer/gradle-download-task#99]
For servers that don't support lastModified, it would be nice if the destination file is only overwritten if it was changed.  Please add an onlyIfChanged flag that does MD5 hashes of the files and compares them, and then only overwrites if the file actually changed...

**Comment by michel-kraemer** [comment]
I'm unsure if I understand how this is supposed to work with HTTP. Can you please elaborate?

**Comment by kenyee** [comment]
With HTTP, you can send up an an if-modified-since header:
  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since
Another way to do it is if you use E-tag headers:
  https://en.wikipedia.org/wiki/HTTP_ETag

Sadly, github supports neither :-(
So the only way to see if a file has changed (I'm trying to download a file from another repo and update if it's different) is if you do an MD5 hash on the file to compare...

**Comment by michel-kraemer** [comment]
Exactly. gradle-download-task does support the `If-Modified-Since` header, and in the next version it will also support ETags.

I still don't understand where the MD5 checksum should come from. Could you provide an example of how you would like to use the plugin. Maybe you could also describe the steps the plugin should perform to check if the file has changed or not.

**Comment by kenyee** [comment]
Sure thing...so the use case is that I have an app that uses the timezone database from the threetenbp library.  You'd specify that the plugin downloads the file into a specific relative filepath in your build.gradle file (e.g., src/res/raw/something.db)
The plugin downloads the file into /tmp/download.tmp initially, then does an MD5 has on it.
It does an MD5 has on the destination file you specify (the something.db).  Then if it's different or the destination doesn't exist, it moves the file from /tmp/download.tmp into the path you specify.

Hope that makes sense...

**Comment by michel-kraemer** [comment]
OK. So what you are saying is that the file will be downloaded to a temporary directory before it is copied to the final location in order to calculate its checksum. Why do you need this extra step? Why don't you download to the final location directly? If the checksum hasn't changed, the file contents have not changed either, so you can safely overwrite the file.

If you always download to a temporary directory you won't save work, you just add an unnecessary copy step. Maybe I'm missing something, but I think your use case can be simplified and you should still get the same results :smile:

**Comment by kenyee** [comment]
That's true...but then the modified date will change.  Though I think git will do the MD5 hash before claiming a file is changed too, so you're probably right :-)

**Comment by michel-kraemer** [comment]
Is your question answered then? If yes, please close the issue. Thanks!

**Comment by kenyee** [comment]
yep..thanks.
